// Filename: app.js
define([
  'jquery',
  'underscore',
  'backbone',
  'router', // Request router.js
], function($, _, Backbone, Router){
  var initialize = function(){
    // Pass in our Router module and call it's initialize function
    Router.initialize();
    
    // Switch from the static content loaded in the HTML to the dynamic content generated by the views
    $("#home").hide();
    $("#page").show();
  }

  return {
    initialize: initialize
  };
});
